Runtime/Scripts/GltFast.cs, Runtime/Scripts/Schema/Sampler.cs
Dear @atteneder , since you were so quick last time, I was wondering:
Would it make sense to still load a model, even if parts of it's linked textures are missing?
I.e. send a warning instead of an error?
In case that the texture gets a 404 here:
```
HTTP/1.1 404 Not Found
UnityEngine.Debug:LogError (object)
GLTFast.GLTFast/<WaitForTextureDownloads>d__58:MoveNext () (at /Users/konrad/Source/glTFast/Runtime/Scripts/GltFast.cs:578)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
```
Then in the  `Apply` method will break and the model can't be loaded. We have a large set of models where modelers sometimes set a material during the modelling procedures but the texture links …
=> null check the texture before applying (Allow models with broken texture linkes to load)

Runtime/Scripts/MaterialGenerator.cs
This is already an improvement, but there are some open questions:
- not sure if the call to SetVector("_MainTex_ST" is still needed now
- for the ShaderGraphMaterialGenerator, the right texture to set these on would be _BaseMap_ST
- I saw TrySetTextureTransform actually takes a propertyId but then ignores it, so that could be directly used; I _think_ the reason it isn't right now is that it's not trivial to also set Rotation?
=> Fix: Texture offset/tiling values getting lost when switching to other shaders

Runtime/Scripts/MaterialGenerator.cs
Instead, set the actual texture's transform values correctly so custom shaders can use that if needed / wanted.
=> Fix error when tryting to set texture offset/scale but material doesn't have _MainTex property.

Runtime/Scripts/ShaderGraphMaterialGenerator.cs, Runtime/Shader/glTF-unlit-Blend-double.shadergraph, Runtime/Shader/glTF-unlit-Blend-double.shadergraph.meta, Runtime/Shader/glTF-unlit-Blend.shadergraph, Runtime/Shader/glTF-unlit-Blend.shadergraph.meta
Fixes #143
I'm not certain about code style here, as Specular/Metallic seem to be doing things different... might need a cleanup pass for consistency.
=> Add unlit-blend ShaderGraph variants

Runtime/Scripts/GltFast.cs
I'm experimenting with using glTFast at edit time (not in Play mode!) and that's going great (will probably do a PR in a while), and stumbled upon this mini issue of glTFast not checking if it's play mode or edit mode time for Destroy operations on generated materials and resources.
This PR fixes that by wrapping Destroy/DestroyImmediate and doing an Application.isPlaying check.
=> fix: safely destroy if GltFast is run in edit mode

Runtime/Scripts/GltFast.cs
If a GLTF had URL query strings as part of its image URLs it GLTFast.cs would not recognize the file format. This was causing problems for me since I was getting GLTFs from a CDN that auto-generated the GLTFs with things like texture version info in the query strings. I fixed this by adding a set of "contains" checks after the "ends with" checks in GLTFast.cs. I added them at the end so that they will only be used if it does not end with a file format since I suspect that this will still be far more common.
=> File format fix

Editor/GltfImporter.cs, Editor/Resources/GltfImporter.uxml, Runtime/Scripts/GameObjectInstantiator.cs, Runtime/Scripts/GltfImport.cs, Runtime/Scripts/ImportSettings.cs
When importing in the editor, it's not always desired to have legacy clips. This PR adds "None" and "Mecanim" as import options.
There's some commented code that attempts to import an AnimatorController + StateMachine as well, but it seems that isn't supported (?) from a ScriptedImporter as it would require adding StateMachine subassets to the AnimatorController subasset.
A workaround (not yet implemented here) would be to have an "Extract AnimatorController" button that creates and connects an AnimatorController as externalObjectMapping.
=> Add: None + Mecanim animation clip import

Runtime/Scripts/GltfImport.cs
A corrupted GLTF file, ie. one without embedded data for textures and buffers will load without error in GLTFast.
@atteneder
=> LoadContent download failed returns successful

Editor/BuiltInShaderGUI.cs
When importing materials with such textures these keywords should be set, as the standard shaders otherwise won't work properly. Might be necessary to additionally check if the shader supports any of these, but there's no good runtime way of checking that as far as I know, so I'd rather make the default shaders work out of the box.
=> Fix: set _METALLICGLOSSMAP and _OCCLUSION keywords in material editor on texture import

Runtime/Scripts/AnimationUtils.cs
This PR avoid to get the wrong `var prevValue = values[0]` for all blendshape curve:
instead of
What do you think about it @atteneder ?
=> Fix first value of curve

Runtime/Scripts/Material/ShaderGraphMaterialGenerator.cs
This fixes the alpha coverage mode for glTF `MASK` mode. The `alphaCutoff` value is used correctly but the material generator assigns the blend shader which is wrong for `MASK` materials. Assigning the opaque shader is correct here. 
Can be tested with this model: [Alpha Blend Mode Test](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest).
=> Fix shader mode selection for glTF MASK mode

Runtime/Scripts/GameObjectInstantiator.cs
In order to make a custom implementation of the GameObjcetInstantiator class which allows to get the references of the different game objects instatntiated in the scene, we need to make the SetNodeName method virtual.
Other similar methods may be in need of overridability.
=> Made SetNodeName method overridable in GameObjectInstantiator class

Runtime/Shader/Built-In/glTFIncludes/glTFUnityStandardCore.cginc, Runtime/Shader/Built-In/glTFIncludes/glTFUnityStandardCoreForwardSimple.cginc
If the gltf model has Topology type Point, as gltfast shaders doesn't set or initialize any number to PSIZE, points are really big on iOS - Vulkan as below.
This PR sets PSIZE to 1 by default so it will fix the point size like this.
This is applied for FowardBase / ForwardAdd / ForwardSimple / Deferred passes of Built-in shaders.
=> Set PSIZE to 1 in VertexOutput

Runtime/Scripts/GameObjectInstantiator.cs
In order to rename the GameObject holding the different nodes with our custom instantiator.
Other similar methods may be in need of overridability.
=> Made AddScene method overridable in GameObjectInstantiator class

Editor/Scripts/EditorDownloadProvider.cs
Probably an autocomplete error. The UnityEngine.Windows.File API is only available for UWP build targets and shouldn't be used elsewhere.
=> Fix: Wrong File API used for reading bytes in EditorDownloadProvider

Editor/Scripts/GltfImporter.cs
This allows users to decide which glTF importer should have precedence.
glTFast is assumed to have the highest priority since its the closest to being"official" right now.
Other importers should properly check for glTFast existance (and potentially other package importer as well) and have lower priority. The pattern here also allows to explicitly define an order, for example these two together would turn on UnityGLTF as default importer:
`UNITYGLTF_FORCE_DEFAULT_IMPORTER_ON`
`GLTFAST_FORCE_DEFAULT_IMPORTER_OFF`
Here's the matching commit in UnityGLTF: https://github.com/prefrontalcortex/UnityGLTF/commit/51d92af70324b0be6397299155ca8efb7cd54df4
If this PR doesn't get in it's not that bad (by default should still work at least with UnityGltf / other known importers that respect glTFast …
=> Feat: allow for turning the ScriptedImporter of glTFast on or off via scripting defines

Editor/Scripts/GltfImporter.cs
Existing files won't be changed since the importer settings are serialized at first creation if they don't exist (good design choice!).
Legacy animation clips don't really make sense to import (can't be used in a number of places), and the additional time required to generate mipmaps isn't as much of a concern for design-time import.
=> Fix: design-time import should use Mecanim by default and generate mipmaps

Runtime/Scripts/GameObjectInstantiator.cs
Users might want to load gltf models on a layer that doesn't get rendered and then make them visible after loading is done.
This PR adds a `layer` member to `GameObjectInstantiator.Settings` which is applied to every `GameObject` being created.
=> Layer support for GameObjectInstantiator

Runtime/Scripts/Export/GltfWriter.cs
When trying to export models from the Unity asset store I was encountering issues with meshes that had more materials assigned than sub-meshes. 
Adding the change in this PR allows the export to take place, though admittedly won't apply the final material to its assigned sub-mesh.
=> Add mesh primitive count check when assigning materials on GLTF export.

Runtime/Scripts/Export/ImageExportBase.cs
Without this checking, for platform with no R8G8B8_UNorm support the following error is given:  Texture creation failed. 'R8G8B8_UNorm' is not supported for Sample usage on this platform.
=> R8G8B8_UNorm not supported issue

Runtime/Scripts/GltfImport.cs
Improves loading performance with complex meshes as tangent creation and mesh creation can happen in a deferred way per primitive.
PR can also be cleanly used on main!
=> Perf: Defer primitive instantiation (tangent creation etc.)

Runtime/Scripts/GameObjectInstantiator.cs
As the name says, makes sure an Animator component is added to imported models when they have animations that are not legacy animations.
=> Feat: Add Animator component when object has animations set to Mecanim

Documentation~/features.md
KHR_lights_punctual is supported for export here: https://github.com/atteneder/glTFast/commit/41793698a2c6f53bd8b480305578e747c4127056
=> Minor fix of the documentation
